
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/product
    password: Rx^JepZZ8MQhd6
  application:
    name: micro-user
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8090
